[tool.black]
line-length = 88
force-exclude = '''
/(
    \.venv
  | \.venv_dev
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true
skip_glob = [
    "**/.venv/*",
    "**/.venv_dev/*",
]

[tool.mypy]
exclude = [
    ".venv",
    ".venv_dev",
]
ignore_missing_imports = true
